sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t thivagars/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true thivagars/docker-react-demo npm run test