version: '3'
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  # For running test cases but not preferred way to do since we can't enter values in the terminal while using the docker-compose.
  # test: 
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   command: ["npm", "run", "test"] # For overriding the coomand in the dockerfile file
